# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Simple_line_plot.py and generate output
      run: |
        python Simple_line_plot.py
    - name: Commit and push output file
      run: |
        git config --global user.name 'lingeshperakasam'
        git config --global user.email 'tbxbush@gmail.com'
        git add .
        git commit -m "Add output file"
        git push

